// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwG3WvpQaBVmzd_nRh4NZw8oslk9qrbLU',
    appId: '1:943379912307:web:cab360caf29b5f0c5fbc06',
    messagingSenderId: '943379912307',
    projectId: 'chat-gpt-4-a6dc1',
    authDomain: 'chat-gpt-4-a6dc1.firebaseapp.com',
    storageBucket: 'chat-gpt-4-a6dc1.appspot.com',
    measurementId: 'G-NKSGVV0ZGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdZFP0CnHsyrTXsPXmztlptcL4Sq85PV0',
    appId: '1:943379912307:android:a5cb24626dcfe3d65fbc06',
    messagingSenderId: '943379912307',
    projectId: 'chat-gpt-4-a6dc1',
    storageBucket: 'chat-gpt-4-a6dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdVWHfg3Y0yTf7KK0jgLr8JddltrKUWE',
    appId: '1:943379912307:ios:7e93e389094d76795fbc06',
    messagingSenderId: '943379912307',
    projectId: 'chat-gpt-4-a6dc1',
    storageBucket: 'chat-gpt-4-a6dc1.appspot.com',
    iosBundleId: 'com.example.gpt4',
  );
}
