// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdZFP0CnHsyrTXsPXmztlptcL4Sq85PV0',
    appId: '1:943379912307:android:80cbe791c97f03785fbc06',
    messagingSenderId: '943379912307',
    projectId: 'chat-gpt-4-a6dc1',
    storageBucket: 'chat-gpt-4-a6dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdVWHfg3Y0yTf7KK0jgLr8JddltrKUWE',
    appId: '1:943379912307:ios:7e93e389094d76795fbc06',
    messagingSenderId: '943379912307',
    projectId: 'chat-gpt-4-a6dc1',
    storageBucket: 'chat-gpt-4-a6dc1.appspot.com',
    androidClientId: '943379912307-643h2m2vsm7omkfe00mp43c7r1usquhu.apps.googleusercontent.com',
    iosClientId: '943379912307-e79pr0otkovjt2k0cl5jrduinlcos3av.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpt4',
  );
}
